config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :personal_data
  
  root "main#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :employments
    accepts_nested_attributes_for :employments, reject_if: :all_blank, allow_destroy: true
end

app/models/employment.rb
class Employment < ApplicationRecord
    validates :employeer, presence: true
    validates :date_started, presence: true
    validates :date_employment_ended, presence: true
    
    belongs_to :employee
end

app/models/personal_datum.rb
class PersonalDatum < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
    validates :phone, presence: true
    validates :phone,   :presence => {:message => 'Phone number invalid'},
                        :length => { :minimum => 12, :maximum => 12,
                                    :message => 'required 10 characters'}

    validates_length_of :first_name, maximum: 25
    validates_length_of :last_name, maximum: 50

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def new
    @employment = Employment.new
  end
  
  def create
    @employee = Employee.new(employment_params)
    respond_to do |format|
      if @employee.save
        format.turbo_stream { render turbo_stream: turbo_stream.prepend('employments', partial: 'employments/employment', locals: {employments: @employee.employments}) }
        format.html { redirect_to employees_url(@employment), notice: "Employment was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employment.errors, status: :unprocessable_entity }
      end
    end
  end


  private

    def employment_params
      params.require(:employee).permit(employments_attributes: [:employeer, :date_started, :date_employment_ended])
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        @personal_data = PersonalDatum.all
        @employments = Employment.all
    end
end

app/controllers/personal_data_controller.rb
class PersonalDataController < ApplicationController
  before_action :ensure_frame_response, only: [:new]

  def new
    @personal_datum = PersonalDatum.new
  end

  def create
    @personal_datum = PersonalDatum.new(personal_datum_params)

    respond_to do |format|
      if @personal_datum.save
        format.turbo_stream { render turbo_stream: turbo_stream.prepend('personal_info', partial: 'personal_data/personal_datum', locals: {personal_datum: @personal_datum}) }
        format.html { redirect_to personal_datum_url(@personal_datum), notice: "personal_data was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @personal_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def personal_datum_params
      params.require(:personal_datum).permit(:first_name, :last_name, :nick_name, :email, :phone)
    end

    def ensure_frame_response
      return unless Rails.env.development?
      redirect_to root_path unless turbo_frame_request?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def error_msg(personal_datum, field_name)
        return unless personal_datum.errors.include?(field_name)
        msg = personal_datum.errors.full_messages_for(field_name).each do |error_message|
                "<ul>
                    <li>#{error_message}</li>
                </ul>".html_safe
                end

        "<div style=\"color: red\">
            #{msg}
        </div>".html_safe
    end
end

app/helpers/personal_data_helper.rb
module PersonalDataHelper
end

app/views/employees/_form.html.slim
.nested-form-wrapper data-new-record="#{f.object.new_record?}" 
  div
    = f.label :employeer, style: "display: block"
    = f.text_field :employeer, required: true, data: { action: "keyup->turbo-modal#checkNestedForm"}
    = error_msg(@employment, :employeer)
  div
    = f.label :date_started, style: "display: block"
    = f.date_field :date_started, data: { action: "change->turbo-modal#checkNestedForm"}
    = error_msg(@employment, :date_started)
  div
    = f.label :date_employment_ended, style: "display: block"
    = f.date_field :date_employment_ended, data: { action: "change->turbo-modal#checkNestedForm"}
    = error_msg(@employment, :date_employment_ended)
  = f.hidden_field :_destroy

app/views/employees/index.html.slim
.w-full
  - if notice.present?
    p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
  .flex.justify-between.items-center
    h1.font-bold.text-4xl Employments
    = button_to 'New employment', new_employee_path, method: :get, data: { turbo_frame: 'modal' }, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium", id:"new_employment"
  #employments.min-w-full
    = render "employments/employment", employments: @employments

app/views/employees/new.html.slim
= turbo_frame_tag "modal" do
  = tag.div data: { controller: "turbo-modal",                                                                                                 
    turbo_modal_target: "modal",                                                                                                               
    action: "turbo:submit-end->turbo-modal#submitEnd keyup@window->turbo-modal#closeWithKeyboard click@window->turbo-modal#closeBackground" }, 
    class: "p-5 bg-slate-300 absolute z-10 top-10 right-10 rounded-md w-96 break-words" do                                                     
    h1.font-bold.text-4xl NewEmployment
    = form_with model: Employee.new, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' } do |f|
      template data-nested-form-target="template" 
        = f.fields_for :employments, Employment.new, child_index: 'NEW_RECORD' do |employment_fields|
          = render "form", f: employment_fields
      = f.fields_for :employments do |employment_fields|
        = render "form", f: employment_fields
      div data-nested-form-target="target" 
      button#add_employee data-action="nested-form#add" type="button"  Add Employee
      = f.submit 'Save', class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"
    = button_tag "Cancel", data: { action: "turbo-modal#hideModal" }, type: "button", class: "rounded-lg py-3 px-5 bg-red-600 text-white"

app/views/employments/_employment.html.slim
- employments.each do |employment|
  div id=("#{dom_id employment}") 
    p.my-5
      strong.block.font-medium.mb-1 Employeer:
      = employment.employeer
    p.my-5
      strong.block.font-medium.mb-1 Date started:
      = employment.date_started
    p.my-5
      strong.block.font-medium.mb-1 Date employment ended:
      = employment.date_employment_ended
  hr/

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title SpaApp
    meta content="width=device-width,initial-scale=1" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    main.container.mx-auto.mt-28.px-5.flex
      = turbo_frame_tag "modal"
      = yield

app/views/main/index.html.slim
= render template: "personal_data/index"
= render template: 'employees/index'

app/views/personal_data/_form.html.slim
= form_with(model: personal_datum) do |form|
  div
    = form.label :first_name, style: "display: block"
    = form.text_field :first_name, required: true, data: { action: "keyup->turbo-modal#checkForm" }
    = error_msg(personal_datum, :first_name)
  div
    = form.label :last_name, style: "display: block"
    = form.text_field :last_name, required: true, data: { action: "keyup->turbo-modal#checkForm"}
    = error_msg(personal_datum, :last_name)
  div
    = form.label :nick_name, style: "display: block"
    = form.text_field :nick_name
    = error_msg(personal_datum, :nick_name)
  div
    = form.label :email, style: "display: block"
    = form.text_field :email, required: true, data: { action: "keyup->turbo-modal#emailValidator" }
    #email-msg
    = error_msg(personal_datum, :email)
  div
    = form.label :phone, style: "display: block"
    = form.text_field :phone, id: "phone", class: "bg-gray-200", required: true, disabled: true, data: { action: "keyup->turbo-modal#phoneValidator" }, :minlength => 12, :maxlength => 12
    div id=("phone-number should") 
    = error_msg(personal_datum, :phone)
  div
    = form.submit "Save", class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"

app/views/personal_data/_personal_datum.html.slim
div id=("#{dom_id personal_datum}") 
  p.my-5
    strong.block.font-medium.mb-1 First Name:
    = personal_datum.first_name
  p.my-5
    strong.block.font-medium.mb-1 Last Name:
    = personal_datum.last_name
  p.my-5
    strong.block.font-medium.mb-1 Nick Name:
    = personal_datum.nick_name
  p.my-5
    strong.block.font-medium.mb-1 Email:
    = personal_datum.email
  p.my-5
    strong.block.font-medium.mb-1 Phone:
    = personal_datum.phone
  hr/

app/views/personal_data/index.html.slim
.w-full
  - if notice.present?
    p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
  .flex.justify-between.items-center
    h1.font-bold.text-4xl Personal Info
    = button_to 'New post', new_personal_datum_path, method: :get, data: { turbo_frame: 'modal' }, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"
  #personal_info.min-w-full
    = render @personal_data

app/views/personal_data/new.html.slim
= turbo_frame_tag "modal" do
  = tag.div data: { controller: "turbo-modal",                                                                                                 
    turbo_modal_target: "modal",                                                                                                               
    action: "turbo:submit-end->turbo-modal#submitEnd keyup@window->turbo-modal#closeWithKeyboard click@window->turbo-modal#closeBackground" }, 
    class: "p-5 bg-slate-300 absolute z-10 top-10 right-10 rounded-md w-96 break-words" do                                                     
    h1.font-bold.text-4xl New Personal Info
    = render "form", personal_datum: @personal_datum
    = button_tag "Cancel", data: { action: "turbo-modal#hideModal" }, type: "button", class: "rounded-lg py-3 px-5 bg-red-600 text-white"